DEFINE ACCLIMATION_LENGTH 300 # 5 minutes
DEFINE BIN_LENGTH 1           # 1 second bins
DEFINE NUM_SAMPLES 3600       # 3600 samples of length 1 second = 1 hour

# no tracking marker
TARGETMARKER(0, 0, 0)

SET(THERMOSTAT, 28)

# Sets the data output counter label to begin at 0, labels data in numerical order
SET(COUNTER1, COUNTER_ZERO)

# bitmap is required in your assets directory
LOAD(ARENAS, "a96embryo.bmp")

# Required for MSD tracking
SET(MSD_MODE, ON)
SET(MSD_THRESHOLD, 5)


ACTION MAIN

    # Turns overhead light and screen off at the start of experiment
    INVOKE(LIGHTS_OFF)

    # Creates headers for columns in the data file
    SET(LOG_STREAM, 0)
    LOGCREATE("TEXT:TIME|TEXT:BIN_NUM")
    LOGAPPEND("TEXT:A1|TEXT:A2|TEXT:A3|TEXT:A4|TEXT:A5|TEXT:A6")
    LOGAPPEND("TEXT:A7|TEXT:A8|TEXT:A9|TEXT:A10|TEXT:A11|TEXT:A12")
    LOGAPPEND("TEXT:A13|TEXT:A14|TEXT:A15|TEXT:A16|TEXT:A17|TEXT:A18")
    LOGAPPEND("TEXT:A19|TEXT:A20|TEXT:A21|TEXT:A22|TEXT:A23|TEXT:A24")
    LOGAPPEND("TEXT:A25|TEXT:A26|TEXT:A27|TEXT:A28|TEXT:A29|TEXT:A30")
    LOGAPPEND("TEXT:A31|TEXT:A32|TEXT:A33|TEXT:A34|TEXT:A35|TEXT:A36")
    LOGAPPEND("TEXT:A37|TEXT:A38|TEXT:A39|TEXT:A40|TEXT:A41|TEXT:A42")
    LOGAPPEND("TEXT:A43|TEXT:A44|TEXT:A45|TEXT:A46|TEXT:A47|TEXT:A48")
    LOGAPPEND("TEXT:A49|TEXT:A50|TEXT:A51|TEXT:A52|TEXT:A53|TEXT:A54")
    LOGAPPEND("TEXT:A55|TEXT:A56|TEXT:A57|TEXT:A58|TEXT:A59|TEXT:A60")
    LOGAPPEND("TEXT:A61|TEXT:A62|TEXT:A63|TEXT:A64|TEXT:A65|TEXT:A66")
    LOGAPPEND("TEXT:A67|TEXT:A68|TEXT:A69|TEXT:A70|TEXT:A71|TEXT:A72")
    LOGAPPEND("TEXT:A73|TEXT:A74|TEXT:A75|TEXT:A76|TEXT:A77|TEXT:A78")
    LOGAPPEND("TEXT:A79|TEXT:A80|TEXT:A81|TEXT:A82|TEXT:A83|TEXT:A84")
    LOGAPPEND("TEXT:A85|TEXT:A86|TEXT:A87|TEXT:A88|TEXT:A89|TEXT:A90")
    LOGAPPEND("TEXT:A91|TEXT:A92|TEXT:A93|TEXT:A94|TEXT:A95|TEXT:A96")
    LOGRUN()

    SET(LOG_STREAM, 0)
    INVOKE(LIGHTS_OFF)
    WAIT(ACCLIMATION_LENGTH)
    VIDEO(99999999999, "developmental_delay_tracking")

    INVOKE(ACTIVITY_SAMPLE, NUM_SAMPLES)

    VIDEOSTOP()

COMPLETE


ACTION ACTIVITY_SAMPLE

    SET(COUNTER1, COUNTER_INC)

    LOGDATA(DATA_SNAPSHOT, "begin")

    WAIT(BIN_LENGTH)

    LOGDATA(DATA_SNAPSHOT, "end")
    LOGDATA(DATA_SELECT, "begin")
    LOGDATA(DATA_DELTA, "end")

    LOGCREATE("RUNTIME|COUNTER1|ARENA_ACTIVITY*")
    LOGRUN()

COMPLETE


ACTION LIGHTS_OFF

    SET(GPO6, 0)
    SET(GPO7, 0)
    SET(GPO8, 0)

COMPLETE


ACTION LIGHTS_ON

    SET(GPO6, 1)
    SET(GPO7, 1)
    SET(GPO8, 1)

COMPLETE

# vim: ft=zanscript
