# define experiment requirements
DEFINE NUM_WELLS 24

DEFINE TIME_BIN 5
DEFINE NUM_SAMPLES 5
DEFINE NUM_BLOCKS 5

DEFINE NUM_VIBRATIONS 5
DEFINE WAIT_TIME 1
DEFINE NUM_ITI 3#00

# define the animal model tracking requirements (dependent on animal size)
SET(TARGET_SIZE,2)
SET(DETECTOR_THRESHOLD,6)

# define auto reference tracking requirements
SET(AUTOREF_MODE,MOVEMENT)
SET(AUTOREF_TIMEOUT,30)

#information about the marker type to track the fish
TargetMarker(0, 0, 0)

# define temperature
SET(THERMOSTAT,28)

# setting up xy coordinate exporting
LOGFILE(1,"XY_data")
SET(LOG_STREAM_PERFRAME,1)


ACTION MAIN

    LOGFILE(0,"DATA_OUTPUT")
    LOGCREATE("TEXT:RUNTIME|TEXT:TEMPERATURE|TEXT:PHASE")

    # completes correct headers and loads arenas
    IF NUM_WELLS = 6
        INVOKE(WELL_6,1)
    ELSEIF NUM_WELLS = 12
        INVOKE(WELL_12,1)
    ELSEIF NUM_WELLS = 24
        INVOKE(WELL_24,1)
    ELSEIF NUM_WELLS = 48
        INVOKE(WELL_48,1)
    ELSEIF NUM_WELLS = 96
        INVOKE(WELL_96,1)
    ENDIF

    LOGRUN()

    SET(LOG_STREAM,1)

    IF NUM_WELLS = 6
        INVOKE(WELL_6_XY,1)
    ELSEIF NUM_WELLS = 12
        INVOKE(WELL_12_XY,1)
    ELSEIF NUM_WELLS = 24
        INVOKE(WELL_24_XY,1)
    ELSEIF NUM_WELLS = 48
        INVOKE(WELL_48_XY,1)
    ELSEIF NUM_WELLS = 96
        INVOKE(WELL_96_XY,1)
    ENDIF

    SET(LOG_STREAM,0)

    INVOKE(LIGHTS_OFF)

    SET(X_DRAWTRACKS,1)

    INVOKE(BLOCK,NUM_BLOCKS)

COMPLETE


#The following lines of code outline the sequence of commands for each BLOCK
ACTION BLOCK

    AUTOREFERENCE()
    SET(LOG_PERFRAME,ON)

    INVOKE(BASELINE,NUM_SAMPLES)

    INVOKE(VIBRATION_SEQUENCE,NUM_VIBRATIONS)
    SET(LOG_PERFRAME,OFF)

COMPLETE


#The following action runs a vibrationn folowed by an intertrial period
ACTION VIBRATION_SEQUENCE

    INVOKE(VIBRATION,1)
    INVOKE(ITI,NUM_ITI)

COMPLETE


# code for collecting data for each sample at each time bin across all the blocks
ACTION BASELINE

    LOGDATA(DATA_SNAPSHOT,"begin")

    WAIT(TIME_BIN)

    LOGDATA(DATA_SNAPSHOT,"end")
    LOGDATA(DATA_SELECT,"begin")
    LOGDATA(DATA_DELTA,"end")

    LOGCREATE("RUNTIME|TEMPERATURE1|TEXT:BASELINE")
    LOGAPPEND("ARENA_DISTANCES:*")
    LOGRUN()

COMPLETE


# The following action collects a 1 second bin of data whilst running a motorcommand.
ACTION VIBRATION

    LOGDATA(DATA_SNAPSHOT,"beginVIB")

    ZCOMMAND("U3 D1190 M1 M-1 M1 M-1 P300 U0 D1190 M1 M-1 M1 M-1")

    #   'M'     Number of Motor steps, the more motor steps, the longer the vibration
    #   'D'     Delay between motor steps (to set motor speed), for d1000 the delay is 4.2 microseconds
    #   'U'     Step mode (0-3, for full/half/quarter/eighth step modes), U3 is the smallest vibration intensity
    #   'P'     Pause, to set delay between motor movements

    WAIT(WAIT_TIME)

    LOGDATA(DATA_SNAPSHOT,"endVIB")
    LOGDATA(DATA_SELECT,"beginVIB")
    LOGDATA(DATA_DELTA,"endVIB")

    LOGCREATE("RUNTIME|TEMPERATURE1|TEXT:VIBRATE")
    LOGAPPEND("ARENA_DISTANCES:*")
    LOGRUN()

COMPLETE


#The following action for collects data in 1 second time bins for the inter trial time (period between vibrations)
ACTION ITI

    LOGDATA(DATA_SNAPSHOT,"beginITI")

    WAIT(WAIT_TIME)

    LOGDATA(DATA_SNAPSHOT,"endITI")
    LOGDATA(DATA_SELECT,"beginITI")
    LOGDATA(DATA_DELTA,"endITI")

    LOGCREATE("RUNTIME|TEMPERATURE1|TEXT:ITI")
    LOGAPPEND("ARENA_DISTANCES:*")
    LOGRUN()

COMPLETE


ACTION LIGHTS_OFF

    SET(GPO6,0)
    SET(GPO7,0)
    SET(GPO8,0)

COMPLETE


###########################################
# settings for different sized arenas
ACTION WELL_6

    LOAD(ARENAS,"a6.bmp")    # This .bmp file is required in assets directory for tracking

    LOGAPPEND("TEXT:A1|TEXT:A2|TEXT:A3|TEXT:A4|TEXT:A5|TEXT:A6")

COMPLETE


ACTION WELL_12

    LOAD(ARENAS,"a12.bmp")    # This .bmp file is required in assets directory for tracking

    LOGAPPEND("TEXT:A1|TEXT:A2|TEXT:A3|TEXT:A4")
    LOGAPPEND("TEXT:B1|TEXT:B2|TEXT:B3|TEXT:B4")
    LOGAPPEND("TEXT:C1|TEXT:C2|TEXT:C3|TEXT:C4")

COMPLETE


ACTION WELL_24

    LOAD(ARENAS,"a24.bmp")    # This .bmp file is required in assets directory for tracking

    LOGAPPEND("TEXT:A1|TEXT:A2|TEXT:A3|TEXT:A4|TEXT:A5|TEXT:A6")
    LOGAPPEND("TEXT:B1|TEXT:B2|TEXT:B3|TEXT:B4|TEXT:B5|TEXT:B6")
    LOGAPPEND("TEXT:C1|TEXT:C2|TEXT:C3|TEXT:C4|TEXT:C5|TEXT:C6")
    LOGAPPEND("TEXT:D1|TEXT:D2|TEXT:D3|TEXT:D4|TEXT:D5|TEXT:D6")

COMPLETE


ACTION WELL_48

    LOAD(ARENAS,"a48.bmp")    # This .bmp file is required in assets directory for tracking

    LOGAPPEND("TEXT:A1|TEXT:A2|TEXT:A3|TEXT:A4|TEXT:A5|TEXT:A6")
    LOGAPPEND("TEXT:A7|TEXT:A8")
    LOGAPPEND("TEXT:B1|TEXT:B2|TEXT:B3|TEXT:B4|TEXT:B5|TEXT:B6")
    LOGAPPEND("TEXT:B7|TEXT:B8")
    LOGAPPEND("TEXT:C1|TEXT:C2|TEXT:C3|TEXT:C4|TEXT:C5|TEXT:C6")
    LOGAPPEND("TEXT:C7|TEXT:C8")
    LOGAPPEND("TEXT:D1|TEXT:D2|TEXT:D3|TEXT:D4|TEXT:D5|TEXT:D6")
    LOGAPPEND("TEXT:D7|TEXT:D8")
    LOGAPPEND("TEXT:E1|TEXT:E2|TEXT:E3|TEXT:E4|TEXT:E5|TEXT:E6")
    LOGAPPEND("TEXT:E7|TEXT:E8")
    LOGAPPEND("TEXT:F1|TEXT:F2|TEXT:F3|TEXT:F4|TEXT:F5|TEXT:F6")
    LOGAPPEND("TEXT:F7|TEXT:F8")

COMPLETE


ACTION WELL_96

    LOAD(ARENAS,"a96.bmp")    # This .bmp file is required in assets directory for tracking

    LOGAPPEND("TEXT:A1|TEXT:A2|TEXT:A3|TEXT:A4|TEXT:A5|TEXT:A6")
    LOGAPPEND("TEXT:A7|TEXT:A8|TEXT:A9|TEXT:A10|TEXT:A11|TEXT:A12")
    LOGAPPEND("TEXT:B1|TEXT:B2|TEXT:B3|TEXT:B4|TEXT:B5|TEXT:B6")
    LOGAPPEND("TEXT:B7|TEXT:B8|TEXT:B9|TEXT:B10|TEXT:B11|TEXT:B12")
    LOGAPPEND("TEXT:C1|TEXT:C2|TEXT:C3|TEXT:C4|TEXT:C5|TEXT:C6")
    LOGAPPEND("TEXT:C7|TEXT:C8|TEXT:C9|TEXT:C10|TEXT:C11|TEXT:C12")
    LOGAPPEND("TEXT:D1|TEXT:D2|TEXT:D3|TEXT:D4|TEXT:D5|TEXT:D6")
    LOGAPPEND("TEXT:D7|TEXT:D8|TEXT:D9|TEXT:D10|TEXT:D11|TEXT:D12")
    LOGAPPEND("TEXT:E1|TEXT:E2|TEXT:E3|TEXT:E4|TEXT:E5|TEXT:E6")
    LOGAPPEND("TEXT:E7|TEXT:E8|TEXT:E9|TEXT:E10|TEXT:E11|TEXT:E12")
    LOGAPPEND("TEXT:F1|TEXT:F2|TEXT:F3|TEXT:F4|TEXT:F5|TEXT:F6")
    LOGAPPEND("TEXT:F7|TEXT:F8|TEXT:F9|TEXT:F10|TEXT:F11|TEXT:F12")
    LOGAPPEND("TEXT:G1|TEXT:G2|TEXT:G3|TEXT:G4|TEXT:G5|TEXT:G6")
    LOGAPPEND("TEXT:G7|TEXT:G8|TEXT:G9|TEXT:G10|TEXT:G11|TEXT:G12")
    LOGAPPEND("TEXT:H1|TEXT:H2|TEXT:H3|TEXT:H4|TEXT:H5|TEXT:H6")
    LOGAPPEND("TEXT:H7|TEXT:H8|TEXT:H9|TEXT:H10|TEXT:H11|TEXT:H12")

COMPLETE


ACTION WELL_6_XY

    LOGCREATE("TEXT:RUNTIME|TEXT:X_A1|TEXT:Y_A1|TEXT:X_A2|TEXT:Y_A2")
    LOGAPPEND("TEXT:X_A3|TEXT:Y_A3|TEXT:X_A4|TEXT:Y_A4")
    LOGAPPEND("TEXT:X_A5|TEXT:Y_A5|TEXT:X_A6|TEXT:Y_A6")
    LOGRUN()

    LOGCREATE("RUNTIME|RAW_XY:A1-6")

COMPLETE


ACTION WELL_12_XY

    LOGCREATE("TEXT:RUNTIME|TEXT:X_A1|TEXT:Y_A1|TEXT:X_A2|TEXT:Y_A2")
    LOGAPPEND("TEXT:X_A3|TEXT:Y_A3|TEXT:X_A4|TEXT:Y_A4")
    LOGAPPEND("TEXT:X_B1|TEXT:Y_B1|TEXT:X_B2|TEXT:Y_B2")
    LOGAPPEND("TEXT:X_B3|TEXT:Y_B3|TEXT:X_B4|TEXT:Y_B4")
    LOGAPPEND("TEXT:X_C1|TEXT:Y_C1|TEXT:X_C2|TEXT:Y_C2")
    LOGAPPEND("TEXT:X_C3|TEXT:Y_C3|TEXT:X_C4|TEXT:Y_C4")
    LOGRUN()

    LOGCREATE("RUNTIME|RAW_XY:A1-12")

COMPLETE


ACTION WELL_24_XY

    LOGCREATE("TEXT:RUNTIME|TEXT:X_A1|TEXT:Y_A1|TEXT:X_A2|TEXT:Y_A2")
    LOGAPPEND("TEXT:X_A3|TEXT:Y_A3|TEXT:X_A4|TEXT:Y_A4")
    LOGAPPEND("TEXT:X_A5|TEXT:Y_A5|TEXT:X_A6|TEXT:Y_A6")
    LOGAPPEND("TEXT:X_B1|TEXT:Y_B1|TEXT:X_B2|TEXT:Y_B2")
    LOGAPPEND("TEXT:X_B3|TEXT:Y_B3|TEXT:X_B4|TEXT:Y_B4")
    LOGAPPEND("TEXT:X_B5|TEXT:Y_B5|TEXT:X_B6|TEXT:Y_B6")
    LOGAPPEND("TEXT:X_C1|TEXT:Y_C1|TEXT:X_C2|TEXT:Y_C2")
    LOGAPPEND("TEXT:X_C3|TEXT:Y_C3|TEXT:X_C4|TEXT:Y_C4")
    LOGAPPEND("TEXT:X_C5|TEXT:Y_C5|TEXT:X_C6|TEXT:Y_C6")
    LOGAPPEND("TEXT:X_D1|TEXT:Y_D1|TEXT:X_D2|TEXT:Y_D2")
    LOGAPPEND("TEXT:X_D3|TEXT:Y_D3|TEXT:X_D4|TEXT:Y_D4")
    LOGAPPEND("TEXT:X_D5|TEXT:Y_D5|TEXT:X_D6|TEXT:Y_D6")

    LOGRUN()

    LOGCREATE("RUNTIME|RAW_XY:A1-24")

COMPLETE


ACTION WELL_48_XY

    LOGCREATE("TEXT:RUNTIME|TEXT:X_A1|TEXT:Y_A1|TEXT:X_A2|TEXT:Y_A2")
    LOGAPPEND("TEXT:X_A3|TEXT:Y_A3|TEXT:X_A4|TEXT:Y_A4")
    LOGAPPEND("TEXT:X_A5|TEXT:Y_A5|TEXT:X_A6|TEXT:Y_A6")
    LOGAPPEND("TEXT:X_A7|TEXT:Y_A7|TEXT:X_A8|TEXT:Y_A8")
    LOGAPPEND("TEXT:X_B1|TEXT:Y_B1|TEXT:X_B2|TEXT:Y_B2")
    LOGAPPEND("TEXT:X_B3|TEXT:Y_B3|TEXT:X_B4|TEXT:Y_B4")
    LOGAPPEND("TEXT:X_B5|TEXT:Y_B5|TEXT:X_B6|TEXT:Y_B6")
    LOGAPPEND("TEXT:X_B7|TEXT:Y_B7|TEXT:X_B8|TEXT:Y_B8")
    LOGAPPEND("TEXT:X_C1|TEXT:Y_C1|TEXT:X_C2|TEXT:Y_C2")
    LOGAPPEND("TEXT:X_C3|TEXT:Y_C3|TEXT:X_C4|TEXT:Y_C4")
    LOGAPPEND("TEXT:X_C5|TEXT:Y_C5|TEXT:X_C6|TEXT:Y_C6")
    LOGAPPEND("TEXT:X_C7|TEXT:Y_C7|TEXT:X_C8|TEXT:Y_C8")
    LOGAPPEND("TEXT:X_D1|TEXT:Y_D1|TEXT:X_D2|TEXT:Y_D2")
    LOGAPPEND("TEXT:X_D3|TEXT:Y_D3|TEXT:X_D4|TEXT:Y_D4")
    LOGAPPEND("TEXT:X_D5|TEXT:Y_D5|TEXT:X_D6|TEXT:Y_D6")
    LOGAPPEND("TEXT:X_D7|TEXT:Y_D7|TEXT:X_D8|TEXT:Y_D8")
    LOGAPPEND("TEXT:X_E1|TEXT:Y_E1|TEXT:X_E2|TEXT:Y_E2")
    LOGAPPEND("TEXT:X_E3|TEXT:Y_E3|TEXT:X_E4|TEXT:Y_E4")
    LOGAPPEND("TEXT:X_E5|TEXT:Y_E5|TEXT:X_E6|TEXT:Y_E6")
    LOGAPPEND("TEXT:X_E7|TEXT:Y_E7|TEXT:X_E8|TEXT:Y_E8")
    LOGAPPEND("TEXT:X_F1|TEXT:Y_F1|TEXT:X_F2|TEXT:Y_F2")
    LOGAPPEND("TEXT:X_F3|TEXT:Y_F3|TEXT:X_F4|TEXT:Y_F4")
    LOGAPPEND("TEXT:X_F5|TEXT:Y_F5|TEXT:X_F6|TEXT:Y_F6")
    LOGAPPEND("TEXT:X_F7|TEXT:Y_F7|TEXT:X_F8|TEXT:Y_F8")

    LOGRUN()

    LOGCREATE("RUNTIME|RAW_XY:A1-48")

COMPLETE


ACTION WELL_96_XY

    LOGCREATE("TEXT:RUNTIME|TEXT:X_A1|TEXT:Y_A1|TEXT:X_A2|TEXT:Y_A2")
    LOGAPPEND("TEXT:X_A3|TEXT:Y_A3|TEXT:X_A4|TEXT:Y_A4")
    LOGAPPEND("TEXT:X_A5|TEXT:Y_A5|TEXT:X_A6|TEXT:Y_A6")
    LOGAPPEND("TEXT:X_A7|TEXT:Y_A7|TEXT:X_A8|TEXT:Y_A8")
    LOGAPPEND("TEXT:X_A9|TEXT:Y_A9|TEXT:X_A10|TEXT:Y_A10")
    LOGAPPEND("TEXT:X_A11|TEXT:Y_A11|TEXT:X_A12|TEXT:Y_A12")

    LOGAPPEND("TEXT:X_B1|TEXT:Y_B1|TEXT:X_B2|TEXT:Y_B2")
    LOGAPPEND("TEXT:X_B3|TEXT:Y_B3|TEXT:X_B4|TEXT:Y_B4")
    LOGAPPEND("TEXT:X_B5|TEXT:Y_B5|TEXT:X_B6|TEXT:Y_B6")
    LOGAPPEND("TEXT:X_B7|TEXT:Y_B7|TEXT:X_B8|TEXT:Y_B8")
    LOGAPPEND("TEXT:X_B9|TEXT:Y_B9|TEXT:X_B10|TEXT:Y_B10")
    LOGAPPEND("TEXT:X_B11|TEXT:Y_B11|TEXT:X_B12|TEXT:Y_B12")

    LOGAPPEND("TEXT:X_C1|TEXT:Y_C1|TEXT:X_C2|TEXT:Y_C2")
    LOGAPPEND("TEXT:X_C3|TEXT:Y_C3|TEXT:X_C4|TEXT:Y_C4")
    LOGAPPEND("TEXT:X_C5|TEXT:Y_C5|TEXT:X_C6|TEXT:Y_C6")
    LOGAPPEND("TEXT:X_C7|TEXT:Y_C7|TEXT:X_C8|TEXT:Y_C8")
    LOGAPPEND("TEXT:X_C9|TEXT:Y_C9|TEXT:X_C10|TEXT:Y_C10")
    LOGAPPEND("TEXT:X_C11|TEXT:Y_C11|TEXT:X_C12|TEXT:Y_C12")

    LOGAPPEND("TEXT:X_D1|TEXT:Y_D1|TEXT:X_D2|TEXT:Y_D2")
    LOGAPPEND("TEXT:X_D3|TEXT:Y_D3|TEXT:X_D4|TEXT:Y_D4")
    LOGAPPEND("TEXT:X_D5|TEXT:Y_D5|TEXT:X_D6|TEXT:Y_D6")
    LOGAPPEND("TEXT:X_D7|TEXT:Y_D7|TEXT:X_D8|TEXT:Y_D8")
    LOGAPPEND("TEXT:X_D9|TEXT:Y_D9|TEXT:X_D10|TEXT:Y_D10")
    LOGAPPEND("TEXT:X_D11|TEXT:Y_D11|TEXT:X_D12|TEXT:Y_D12")

    LOGAPPEND("TEXT:X_E1|TEXT:Y_E1|TEXT:X_E2|TEXT:Y_E2")
    LOGAPPEND("TEXT:X_E3|TEXT:Y_E3|TEXT:X_E4|TEXT:Y_E4")
    LOGAPPEND("TEXT:X_E5|TEXT:Y_E5|TEXT:X_E6|TEXT:Y_E6")
    LOGAPPEND("TEXT:X_E7|TEXT:Y_E7|TEXT:X_E8|TEXT:Y_E8")
    LOGAPPEND("TEXT:X_E9|TEXT:Y_E9|TEXT:X_E10|TEXT:Y_E10")
    LOGAPPEND("TEXT:X_E11|TEXT:Y_E11|TEXT:X_E12|TEXT:Y_E12")

    LOGAPPEND("TEXT:X_F1|TEXT:Y_F1|TEXT:X_F2|TEXT:Y_F2")
    LOGAPPEND("TEXT:X_F3|TEXT:Y_F3|TEXT:X_F4|TEXT:Y_F4")
    LOGAPPEND("TEXT:X_F5|TEXT:Y_F5|TEXT:X_F6|TEXT:Y_F6")
    LOGAPPEND("TEXT:X_F7|TEXT:Y_F7|TEXT:X_F8|TEXT:Y_F8")
    LOGAPPEND("TEXT:X_F9|TEXT:Y_F9|TEXT:X_F10|TEXT:Y_F10")
    LOGAPPEND("TEXT:X_F11|TEXT:Y_F11|TEXT:X_F12|TEXT:Y_F12")

    LOGAPPEND("TEXT:X_G1|TEXT:Y_G1|TEXT:X_G2|TEXT:Y_G2")
    LOGAPPEND("TEXT:X_G3|TEXT:Y_G3|TEXT:X_G4|TEXT:Y_G4")
    LOGAPPEND("TEXT:X_G5|TEXT:Y_G5|TEXT:X_G6|TEXT:Y_G6")
    LOGAPPEND("TEXT:X_G7|TEXT:Y_G7|TEXT:X_G8|TEXT:Y_G8")
    LOGAPPEND("TEXT:X_G9|TEXT:Y_G9|TEXT:X_G10|TEXT:Y_G10")
    LOGAPPEND("TEXT:X_G11|TEXT:Y_G11|TEXT:X_G12|TEXT:Y_G12")

    LOGAPPEND("TEXT:X_H1|TEXT:Y_H1|TEXT:X_H2|TEXT:Y_H2")
    LOGAPPEND("TEXT:X_H3|TEXT:Y_H3|TEXT:X_H4|TEXT:Y_H4")
    LOGAPPEND("TEXT:X_H5|TEXT:Y_H5|TEXT:X_H6|TEXT:Y_H6")
    LOGAPPEND("TEXT:X_H7|TEXT:Y_H7|TEXT:X_H8|TEXT:Y_H8")
    LOGAPPEND("TEXT:X_H9|TEXT:Y_H9|TEXT:X_H10|TEXT:Y_H10")
    LOGAPPEND("TEXT:X_H11|TEXT:Y_H11|TEXT:X_H12|TEXT:Y_H12")

    LOGRUN()

    LOGCREATE("RUNTIME|RAW_XY:A1-96")

COMPLETE

# vim: ft=zanscript
